# Generated by Django 4.2.6 on 2024-04-09 22:01

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.AutoField(primary_key=True, serialize=False)),
                ('dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=255, null=True), blank=True, default=None, null=True, size=None)),
                ('measures', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=None, null=True), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_auto_params_forecast', models.BooleanField(blank=True, default=False, null=True)),
                ('p_value', models.IntegerField(blank=True, default=None, null=True)),
                ('q_value', models.IntegerField(blank=True, default=None, null=True)),
                ('d_value', models.IntegerField(blank=True, default=None, null=True)),
                ('forecast_measures', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=None, null=True), size=None)),
                ('n_count', models.IntegerField(blank=True, default=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('visualization_id', models.AutoField(primary_key=True, serialize=False)),
                ('visualization_type', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prognosis.dataset')),
                ('forecast', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='prognosis.forecast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prognosis.visualization')),
            ],
        ),
    ]
