# Generated by Django 4.2.6 on 2024-04-09 22:17

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('forecast_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_auto_params_forecast', models.BooleanField()),
                ('p_value', models.IntegerField()),
                ('q_value', models.IntegerField()),
                ('d_value', models.IntegerField()),
                ('forecast_measures', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('n_count', models.IntegerField()),
                ('dimensions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, default=None, null=True, size=None)),
                ('measures', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('visualization_type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('unit', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
